---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
    customize:
      cpus: 2
      memory: 1024
    network:
      - ["private_network", {ip: "11.12.14.14"}]
  run_list:
  - recipe[apt]
suites:
- name: default
  run_list:
    - recipe[hipsnip-jetty_test::jetty_9]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/jetty_9_test.rb"
- name: jetty-8
  run_list:
    - recipe[hipsnip-jetty_test::jetty_8]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/jetty_8_test.rb"
- name: logging-on-files
  run_list:
    - recipe[hipsnip-jetty_test::logging_on_files]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/logging_on_files_test.rb"
- name: use-syslog-jetty-9
  run_list:
    - recipe[hipsnip-jetty_test::use_syslog_jetty_9]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/use_syslog_jetty_9_test.rb"
- name: use-syslog-jetty-8
  run_list:
    - recipe[hipsnip-jetty_test::use_syslog_jetty_8]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/use_syslog_jetty_8_test.rb"